config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'
  get 'about' => 'public/homes#about'

  get 'items' => 'public/items#index'
  get 'items/:id', to: 'public/items#show', as: 'item'

  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/complete' => 'public/orders#complete'

  delete 'cart_items/destroy_all' => 'public/cart_items#all_destroy', as: 'all_destroy'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

  scope module: 'public' do
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :public do
  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :create, :new, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end

  devise_for :customer,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :orders
  has_many :order_details

  attachment :image

  def with_tax_price #消費税
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "登録しました。"
      redirect_to admin_item_path(@item)
    else
      render 'new'
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "更新しました。"
      redirect_to admin_item_path(@item.id)
    else
      render 'edit'
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row justify-content-center offset-1">
    <div class="col-9">
      <h4>商品編集</h4>
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :introduction %></td>
          </tr>
          <tr>
            <td>税抜価格</td>
            <td><%= f.text_field :price %>円</td>
          </tr>
        </tbody>
      </table>
      <div class="col-7 text-center">
        <%= f.submit '変更を保存', class: "btn btn-success btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8">
      <br>
      <div class="text-right">
        <%= link_to "新規登録", new_admin_item_path, class:"btn btn-primary" %>
      </div>
      <h4>商品一覧</h4>
      <table class="table table-sm">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
          <tr>
            <th><%= item.id %></th>
            <td><u><%= link_to item.name, admin_item_path(item), style: "color: black;" %></u></td>
            <td><%= item.price %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row justify-content-center offset-1">
    <div class="col-9">
      <h4>商品新規登録</h4>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品画像</td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :introduction %></td>
          </tr>
          <tr>
            <td>税抜価格</td>
            <td><%= f.text_field :price %>円</td>
          </tr>
        </tbody>
      </table>
      <div class="col-7 text-center">
        <%= f.submit '新規登録', class: "btn btn-success btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row justify-content-center offset-2">
    <div class="col-3">
      <p class="text-success"><%= flash[:notice] %></p>
      <h3>商品詳細</h3><br>
      <%= attachment_image_tag @item, :image, format: 'jpeg', size: "200x150", fallback:"no_image.jpg" %>
    </div>
    <div class="col-7">
      <table class="table-borderless"><br>
      <br>
      <br>
        <tbody>
          <tr>
            <td>商品名</td>
            <td>　<%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td>　<%= @item.introduction %></td>
          </tr>
          <tr>
            <td>税込価格<br>(税抜価格)</td>
            <td>　<%= @item.with_tax_price %>(<%= @item.price %>)円</td>
          </tr>
        </tbody>
      </table>
      <br>
      <br>
      <br>
      <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>