config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'
  get 'about' => 'public/homes#about'

  get 'items' => 'public/items#index'
  get 'items/:id', to: 'public/items#show', as: 'item'

  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/complete' => 'public/orders#complete'

  delete 'cart_items/destroy_all' => 'public/cart_items#all_destroy', as: 'all_destroy'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

  scope module: 'public' do
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :public do
  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :create, :new, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end

  devise_for :customer,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "更新しました。"
      redirect_to admin_customer_path(@customer)
    else
      render 'edit'
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 text-left">
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報</h4>
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= f.text_field :last_name %> <%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><%= f.radio_button :is_deleted, false %><%= f.label :is_deleted, "有効" %>
                <%= f.radio_button :is_deleted, true %><%= f.label :is_deleted, "退会" %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="col text-center">
        <%= f.submit '変更を保存', class: "btn btn-success btn-lg " %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="col-2 offset-2 text-center">
    <h4>会員一覧</h4>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-8">
      <table class="table table-sm">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><u><%= link_to customer.last_name + " " + customer.first_name, admin_customer_path(customer), style: "color: black;" %></u></td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted %>
                  <p class="text-secondary"><strong>退会</strong></p>
                <% else %>
                  <p class="text-success"><strong>有効</strong></p>
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 text-left">
      <p class="text-success"><%= flash[:notice] %></p>
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
      <table class="table table-borderless">
        <tbody>
          <tr>
           <td>会員ID</td>
           <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><% if @customer.is_deleted %>
                  <p class="text-secondary"><strong>退会</strong></p>
                <% else %>
                  <p class="text-success"><strong>有効</strong></p>
                <% end %>
              </td>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <div class="col-7 text-right">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
        </div>
        <div class="col-5 text-center">
          <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>