config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'
  get 'about' => 'public/homes#about'

  get 'items' => 'public/items#index'
  get 'items/:id', to: 'public/items#show', as: 'item'

  post 'orders/confirm' => 'public/orders#confirm'
  get 'orders/complete' => 'public/orders#complete'

  delete 'cart_items/destroy_all' => 'public/cart_items#all_destroy', as: 'all_destroy'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

  scope module: 'public' do
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :public do
  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :create, :new, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
  end

  devise_for :customer,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h4>注文履歴詳細</h4>
  <table class="col-7 table table-borderless">
    <tbody>
      <tr>
        <th>購入者</th>
        <td><u><%= link_to @order.customer.last_name + " " + @order.customer.first_name, admin_customer_path(@order.customer), style: "color: black;" %></u></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.address %></th>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <div class="col-8">
      <table class="table table-sm">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.with_tax_price %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.subtotal %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-3 offset-1">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <th><%= @order.total_payment.to_s(:delimited) %>円</th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>